name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, macos, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          python build.py ${{ matrix.os }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Raccoon2_BOINC_Installer_${{ matrix.os }}
          path: |
            raccoon2_boinc_installer.py
            README.md
